permalink: /:year:month:day/:title
url: player1-z.github.io #Your url here
baseurl: 

# variables
name: Player 1 - Z
description: Cyberspace of Z
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
